// <auto-generated />
using System;
using MecaPlan.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MecaPlan.Infrastructure.Migrations
{
    [DbContext(typeof(MecaPlanDbContext))]
    [Migration("20260826210945_Sp2ProjectIdeaBom")]
    partial class Sp2ProjectIdeaBom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MecaPlan.Domain.Entities.BomProyecto", b =>
                {
                    b.Property<int>("BOMID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BOMID"));

                    b.Property<int>("CantidadRequerida")
                        .HasColumnType("int");

                    b.Property<int>("ComponenteID")
                        .HasColumnType("int");

                    b.Property<int>("ProyectoID")
                        .HasColumnType("int");

                    b.HasKey("BOMID");

                    b.HasIndex("ComponenteID");

                    b.HasIndex("ProyectoID", "ComponenteID")
                        .IsUnique();

                    b.ToTable("BOMProyectos", "Proyectos");
                });

            modelBuilder.Entity("MecaPlan.Domain.Entities.Componente", b =>
                {
                    b.Property<int>("ComponenteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComponenteID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ComponenteID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Componentes", "Inventario");
                });

            modelBuilder.Entity("MecaPlan.Domain.Entities.Estudiante", b =>
                {
                    b.Property<int>("EstudianteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Carnet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailNormalizado")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EstadoBit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("EstudianteID");

                    b.HasIndex("Carnet")
                        .IsUnique()
                        .HasDatabaseName("UX_Estudiantes_Carnet");

                    b.HasIndex("EmailNormalizado")
                        .IsUnique()
                        .HasDatabaseName("UX_Estudiantes_EmailNormalizado");

                    b.ToTable("Estudiantes", "Seguridad");
                });

            modelBuilder.Entity("MecaPlan.Domain.Entities.EventoAutenticacion", b =>
                {
                    b.Property<int>("IdEventoAutenticacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEventoAutenticacion"));

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EstudianteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrigenMinimizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEventoAutenticacion");

                    b.ToTable("EventosAutenticacion", "Seguridad");
                });

            modelBuilder.Entity("MecaPlan.Domain.Entities.Proyecto", b =>
                {
                    b.Property<int>("ProyectoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProyectoID"));

                    b.Property<string>("DescripcionIdea")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("EstudianteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ProyectoID");

                    b.HasIndex("EstudianteID");

                    b.ToTable("Proyectos", "Proyectos");
                });

            modelBuilder.Entity("MecaPlan.Domain.Entities.BomProyecto", b =>
                {
                    b.HasOne("MecaPlan.Domain.Entities.Componente", "Componente")
                        .WithMany()
                        .HasForeignKey("ComponenteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecaPlan.Domain.Entities.Proyecto", null)
                        .WithMany("EntradasBom")
                        .HasForeignKey("ProyectoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Componente");
                });

            modelBuilder.Entity("MecaPlan.Domain.Entities.Proyecto", b =>
                {
                    b.Navigation("EntradasBom");
                });
#pragma warning restore 612, 618
        }
    }
}
